# Create a program that will play the “cows and bulls” game with the user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number(Digits should not be repeated). For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:

#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1250
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.

# import random

# # Generate a list of digits from 0 to 9
# digits = list(range(10))

# # Shuffle the list to randomize the order of digits
# random.shuffle(digits)

# # Ensure that the first digit is not 0 (to make it a 4-digit number)
# if digits[0] == 0:
#     digits[0], digits[1] = digits[1], digits[0]  # Swap 0 with another digit

# # Select the first four digits to form a 4-digit number
# random_number = ''.join(map(str, digits[:4]))

# print("Welcome to the Guess The Number Game")
# print("You have to guess 4 digits")
# print("You will get Cow if you guess right digit at right place and Bull if you guess right digit at wrong place")
# print("Let's Start")

# retry_count=0

# def get_number(prompt):
#     return int(input(prompt))

# while True:
#     cows=0
#     bulls=0
#     in_num=get_number("Enter the 4 digit number")

#     if(in_num==random_number):
#         print("You Guessed it right. Number was :", in_num)
#         print(f"You took {retry_count} tries to guess")
#         break
#     else:
#         for i in range(4):
#             if in_num[i] == random_number[i]:
#                 cows += 1
#             elif in_num[i] in random_number:
#                 bulls += 1
#         retry_count += 1
#         print(f"cows: {cows}, bulls: {bulls}")

import random

print("Welcome to the Guess The Number Game")
print("You have to guess 4 digits")
print("You will get Cow if you guess the right digit at the right place and Bull if you guess the right digit at the wrong place")
print("Let's Start")

# Generate a random 4-digit number without duplicate digits
digits = list(range(10))
random.shuffle(digits)
random_number = ''.join(map(str, digits[:4]))

retry_count = 0

def get_number(prompt):
    return input(prompt)

while True:
    cows = 0
    bulls = 0
    in_num = int(get_number("Enter the 4 digit number: "))

    if in_num == int(random_number):
        print("You Guessed it right. Number was:", in_num)
        print(f"You took {retry_count} tries to guess")
        break
    else:
        for i in range(4):
            if in_num // 10**(3-i) % 10 == int(random_number[i]):
                cows += 1
            elif int(random_number[i]) in [int(d) for d in str(in_num)]:
                bulls += 1
        retry_count += 1
        print(f"cows: {cows}, bulls: {bulls}")



